{{ if .Values.global.syntheticsWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.syntheticsWorker.additionalAnnotations }}
{{ toYaml .Values.syntheticsWorker.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: synthetics-worker
    app.kubernetes.io/name: synthetics-worker
    {{- if .Values.syntheticsWorker.additionalLabels }}
{{ toYaml .Values.syntheticsWorker.additionalLabels | indent 4 }}
    {{- end }}
  name: synthetics-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.syntheticsWorker.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: synthetics-worker
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
        {{- if .Values.syntheticsWorker.additionalAnnotations }}
{{ toYaml .Values.syntheticsWorker.additionalAnnotations | indent 8 }}
        {{- end }}
        {{- if .Values.syntheticsWorker.podAnnotations }}
{{ toYaml .Values.syntheticsWorker.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: synthetics-worker
        app.kubernetes.io/name: synthetics-worker
        {{- include "groundcover.labels" . | nindent 8 }}
        {{- if .Values.syntheticsWorker.additionalLabels }}
{{ toYaml .Values.syntheticsWorker.additionalLabels | indent 8 }}
        {{- end }}
        {{- if .Values.syntheticsWorker.podLabels }}
{{ toYaml .Values.syntheticsWorker.podLabels | indent 8 }}
        {{- end }}
    spec:
{{- if .Values.syntheticsWorker.tolerations }}
      tolerations:
{{ toYaml .Values.syntheticsWorker.tolerations | indent 8 }}
{{- end }}
{{- if .Values.syntheticsWorker.affinity }}
      affinity:
{{ toYaml .Values.syntheticsWorker.affinity | indent 8 }}
{{- end }}
{{- if .Values.syntheticsWorker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.syntheticsWorker.nodeSelector | indent 8 }}
{{- end }}
      imagePullSecrets: {{ include "imagePullSecrets" . }}
      containers:
      - env:
        - name: GC_RUNNINGNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GC_GROUNDCOVERVERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['groundcover_version']
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        {{- with .Values.syntheticsWorker.env }}
          {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.syntheticsWorker.builtinEnv }}
          {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{include "groundcover.config.secretName" .}}
        image: {{ tpl .Values.syntheticsWorker.image.repository . }}:{{ tpl .Values.syntheticsWorker.image.tag . }}
        imagePullPolicy: Always
        name: synthetics-worker
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          {{ toYaml .Values.syntheticsWorker.readinessProbe | nindent 10 }}
        livenessProbe:
          {{ toYaml .Values.syntheticsWorker.livenessProbe | nindent 10 }}
        resources:
{{- toYaml .Values.syntheticsWorker.resources | nindent 10 }}
{{- if .Values.syntheticsWorker.priorityClassName }}
      priorityClassName: {{ .Values.syntheticsWorker.priorityClassName }}
{{- end }}
{{ end }}


