{{- if .Values.keeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keeper.headless.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: raft
      protocol: TCP
      port: {{ .Values.keeper.ports.raft }}
      targetPort: {{ .Values.keeper.ports.raft }}
  selector:
    {{- include "keeper.selectorLabels" . | nindent 4 }}
{{- end }}
