{{ if and .Values.global.backend.enabled .Values.global.dispatchCenter.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if .Values.dispatchCenter.additionalAnnotations }}
{{ toYaml .Values.dispatchCenter.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: dispatch-center
    app.kubernetes.io/name: dispatch-center
    {{- if .Values.dispatchCenter.additionalLabels }}
{{ toYaml .Values.dispatchCenter.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "dispatch-center.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: dispatch-center
  type: ClusterIP
{{ end -}}

