{{ if .Values.portal.backendSettings.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: {{ include "portal.fullname" . }}-backend-settings
  namespace: {{ .Release.Namespace }}
data:
  backend-settings.yaml: |-
{{- if .Values.portal.backendSettings.config }}
{{ tpl (toYaml .Values.portal.backendSettings.config) . | nindent 4 }}
{{- end }}
{{ end -}}