{{- if .Values.global.cnpg.upgradeCRDs }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cnpg-crds.fullname" . }}
  annotations:
  {{- include "cnpg-crds.rbac.annotations" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cnpg-crds.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cnpg-crds.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}