{{- if .Values.global.cnpg.upgradeCRDs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cnpg-crds.fullname" . }}
  annotations:
  {{- include "cnpg-crds.configmap.annotations" . | nindent 4 }}
data:
{{ (.Files.Glob "crds/crds.yaml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cnpg-crds.fullname" . }}-clusters
  annotations:
  {{- include "cnpg-crds.configmap.annotations" . | nindent 4 }}
data:
{{ (.Files.Glob "crds/clusters.yaml").AsConfig | indent 2 }}

{{- end }}