{{- if .Values.global.cnpg.upgradeCRDs }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnpg-crds.fullname" . }}
  annotations:
  {{- include "cnpg-crds.rbac.annotations" $ | nindent 4 }}
{{- end }}