{{- $agentService := include "agent-service.values" . | fromYaml }}
{{- if $agentService.enabled | default false }}
{{- if $agentService.serviceAccount }}
{{- if not (eq $agentService.serviceAccount.create false) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $agentService.serviceAccount.name | default (include "agent-service.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agent-service.fullname" . }}
    {{- include "groundcover.labels" . | nindent 4 }}
  {{- with $agentService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
