{{- if index .Values "agent-service" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-service
  labels:
    app: {{ .Release.Name }}-agent-service
    {{- include "groundcover.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values "agent-service" "service" "port" }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-agent-service
{{- end }}
