{{- if .Values.global.temporal.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-schema-files
  namespace: {{ .Release.Namespace }}
  {{- with .Values.temporalConfig.schemaConfigMaps.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: schema
data:
  {{- $files := .Files }}
  {{- range $path, $_ := .Files.Glob "sql-schemas/temporal/*.sql" }}
  {{- $fileName := base $path }}
  {{ $fileName | replace "." "_" }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
  {{- range $path, $_ := .Files.Glob "sql-schemas/temporal/versioned/**/*.sql" }}
  {{- $fileName := base $path }}
  {{- $dirName := base (dir $path) }}
  {{ printf "%s_%s" $dirName $fileName | replace "." "_" }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-visibility-schema-files
  namespace: {{ .Release.Namespace }}
  {{- with .Values.temporalConfig.schemaConfigMaps.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: schema
data:
  {{- $files := .Files }}
  {{- range $path, $_ := .Files.Glob "sql-schemas/visibility/*.sql" }}
  {{- $fileName := base $path }}
  {{ $fileName | replace "." "_" }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
  {{- range $path, $_ := .Files.Glob "sql-schemas/visibility/versioned/**/*.sql" }}
  {{- $fileName := base $path }}
  {{- $dirName := base (dir $path) }}
  {{ printf "%s_%s" $dirName $fileName | replace "." "_" }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
{{- end }}