apiVersion: v2
appVersion: 1.11.219
dependencies:
- condition: global.temporal.enabled
  name: temporal
  repository: https://go.temporal.io/helm-charts
  version: 0.72.0
description: groundcover's Temporal Helm chart
name: temporal
type: application
version: 1.11.219
