{{- if and (eq .Values.global.auth.type "no-auth") (eq .Values.global.auth.enabled true) -}}
{{- $globalKongIngressAnnotations := default (dict) .Values.onprem.kongIngressAnnotations }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- $noAuthAnnotations := mergeOverwrite (dict) $globalKongIngressAnnotations (dict "konghq.com/protocols" "http,https") }}
  annotations:
    {{- range $key, $value := $noAuthAnnotations }}
    {{- printf "%s: %s" $key ($value | quote) | nindent 4 }}
    {{- end }}
  name: router-no-auth-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
  rules:
  - host: {{ .Values.frontendDomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.auth.proxyService }}
            port:
              number: {{ .Values.auth.proxyPort }}
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if $globalKongIngressAnnotations }}
  annotations:
    {{- range $key, $value := $globalKongIngressAnnotations }}
    {{- printf "%s: %s" $key ($value | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: router-no-auth-api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: router
            port:
              number: 8080
        path: /api
        pathType: Prefix
{{- end -}}
