{{- if and .Values.global.backend.enabled .Values.global.pdfReportWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if .Values.pdfReportWorker.additionalAnnotations }}
{{ toYaml .Values.pdfReportWorker.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: pdf-report-worker
    app.kubernetes.io/name: pdf-report-worker
    {{- if .Values.pdfReportWorker.additionalLabels }}
{{ toYaml .Values.pdfReportWorker.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "pdf-report-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: pdf-report-worker
  type: ClusterIP
{{- end }}
