{{- /* TODO: Remove the sourceMaps.enabled guard once IAM permissions are enabled by default */}}
{{- if and .Values.global.ingestor.enabled .Values.global.backend.enabled .Values.ingestor.rum.sourceMaps.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: ingestor
{{- if and .Values.ingestor.serviceAccount .Values.ingestor.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.ingestor.serviceAccount.annotations | indent 4 }}
{{- end }}
  name: {{ include "ingestor.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
